name: Bump Homebrew Formula
on:
  push:
    branches: [main]
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Extract version
        id: extract-version
        run: |
          echo "tag-name=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: rando_lgtm
          formula-path: rando_lgtm.rb
          homebrew-tap: yossydev/homebrew-RandoLGTM
          base-branch: main
          download-url: https://github.com/yossydev/RandoLGTM/archive/refs/tags/${{ steps.extract-version.outputs.tag-name }}.tar.gz
          commit-message: |
            rando_lgtm ${{ steps.extract-version.outputs.tag-name }}
            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
