name: Bump Homebrew Formula
on:
  push:
    tags: "v*"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: rando_lgtm
          formula-path: rando_lgtm.rb
          homebrew-tap: yossydev/homebrew-RandoLGTM
          base-branch: main
          download-url: https://github.com/yossydev/rando_lgtm/archive/refs/tags/${{ github.ref_name }}.tar.gz
          commit-message: |
            rando_lgtm ${{ github.ref_name }}
            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
